"""empty message

Revision ID: 790de3705507
Revises: 
Create Date: 2019-11-21 23:30:21.374077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790de3705507'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=True),
    sa.Column('preco_custo', sa.Float(), nullable=True),
    sa.Column('preco_venda', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto')
    # ### end Alembic commands ###
